# Generated by Django 3.2.5 on 2021-08-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[(1, 'Weak'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest')], max_length=20),
        ),
    ]
